### PR TITLE
Work mostly done on responsiveness, also adds a mobile menu

### PR DESCRIPTION
**Pull request by wellingtongvs**
Tested with Emmet Re:view on Android and Apple phones, should be working pretty nicely on most sizes.
Issue: https://github.com/RefugeRestrooms/refugerestrooms/issues/468

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Hi @wellingtongvs,

Thanks for this! I will look at it right away!

**Comment by DeeDeeG** [comment]
I can't be too picky, since I didn't have time (and perhaps the knowledge) to finish this myself. But In general I think it would be nice to accomplish this with fewer CSS rules, if possible.

I wouldn't consider this a blocker, especially for merging into a mockup. But hopefully we can keep the CSS relatively lean in the final implementation. (Not that the existing CSS in the web app is super tiny, though.)

If you'd like to re-factor to use less styles before merging this, please let me know. And if you would rather spend time on the actual implementation over at [`refugerestrooms/refugerestrooms`](https://github.com/refugerestrooms/refugerestrooms), or call it a day with regard to the mockup, (understandable) I will just merge as-is. I am fine either way.

Thanks again for your work on this!

**Comment by DeeDeeG** [comment]
Another thing: Even if it gets a bit cramped, I think we can keep the search bar on one row for some narrow screen widths, like 320px (width of the original iPhone and several iPhones since then). On one row with less room to breathe is still better than the buttons being below, in my view.

Just need to reduce its margins or padding.

Edit to clarify: We can address that in this pull request or at the final implementation. Just wanted to note that down.

**Comment by wellingtongvs** [comment]
> Another thing: Even if it gets a bit cramped, I think we can keep the search bar on one row for some narrow screen widths, like 320px (width of the original iPhone and several iPhones since then). On one row with less room to breathe is still better than the buttons being below, in my view.
> 
> Just need to reduce its margins or padding.
> 
> Edit to clarify: We can address that in this pull request or at the final implementation. Just wanted to note that down.

I added a new commit to fix that! 

> I can't be too picky, since I didn't have time (and perhaps the knowledge) to finish this myself. But In general I think it would be nice to accomplish this with fewer CSS rules, if possible.
> 
> I wouldn't consider this a blocker, especially for merging into a mockup. But hopefully we can keep the CSS relatively lean in the final implementation. (Not that the existing CSS in the web app is super tiny, though.)
> 
> If you'd like to re-factor to use less styles before merging this, please let me know. And if you would rather spend time on the actual implementation over at [`refugerestrooms/refugerestrooms`](https://github.com/refugerestrooms/refugerestrooms), or call it a day with regard to the mockup, (understandable) I will just merge as-is. I am fine either way.
> 
> Thanks again for your work on this!

I think I'd rather spend time on the actual implementation, if possible. I'm sure that spending a little more time on this would probably help out a bit on the final implementation, but since the actual repository probably already has some CSS that could be reused to make it easier to implement this with fewer rules (and even more so if we keep using Bootstrap) I'd rather spend my time working over there.

Also, if you have any tips or suggestions on what classes I should refactor/alter/remove, I'd appreciate it a lot. 

Thank you for your patience!

**Comment by DeeDeeG** [comment]
Looks good! Thank you!

**Comment by DeeDeeG** [comment]
> I think I'd rather spend time on the actual implementation, if possible. [. . .] the actual repository probably already has some CSS that could be reused to make it easier to implement this with fewer rules (and even more so if we keep using Bootstrap) [. . .] .

Yes, I agree. That sounds right.

> Also, if you have any tips or suggestions on what classes I should refactor/alter/remove, I'd appreciate it a lot.

We can look more closely at this during the actual implementation, of course.

In general, my thoughts on best practices for CSS are as follows: 

- I hope to tend toward using fewer and simpler [CSS rules](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax#CSS_selectors_and_rules) when possible, 
  - and neat, easy-to-understand [selectors](https://developer.mozilla.org/en-US/docs/Glossary/CSS_Selector) where possible
- And hopefully classes and ids will have names that are easy to guess what they mean, and that are also easy to understand when inspecting the page. 
- Related, but not strictly CSS: It helps to have semantic HTML. (Which, so far, I think we do pretty well in the web app.) So you can select `<nav>` with CSS, or `<main>` etc.

Thanks again!

**Pull request merged**
